#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 18 14:32:57 2017

@author: apple
"""

import pylab

x = [1,2,3]
y = [4,5,6]
x1 = pylab.array(x)
y1 = pylab.array(y)

try:
    print x*y1
except TypeError:
    print "can't multiply %s and %s" %(type(x),type(y))


print 2*y1
print x1*y1
